
# Netlify configuration file

# This rule redirects all paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specify build settings if needed
[build]
  publish = "dist"
  command = "npm run build"
