
-- Add category column to giftbit_brands
ALTER TABLE public.giftbit_brands ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'Other';

-- Backfill existing brands with categories based on name patterns
UPDATE public.giftbit_brands SET category = CASE
  -- Prepaid Cards
  WHEN LOWER(name) LIKE '%visa%' THEN 'Prepaid Cards'
  WHEN LOWER(name) LIKE '%mastercard%' THEN 'Prepaid Cards'
  WHEN LOWER(name) LIKE '%prepaid%' THEN 'Prepaid Cards'
  WHEN LOWER(name) LIKE '%eftpos%' THEN 'Prepaid Cards'
  -- Apparel
  WHEN LOWER(name) LIKE '%adidas%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%nike%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%h&m%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%zara%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%uniqlo%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%lululemon%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%gap%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%foot locker%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%cotton on%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%bonds%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%rebel%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%platypus%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%the iconic%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%country road%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%seed%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%kathmandu%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%r.m.williams%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%surfstitch%' THEN 'Apparel'
  WHEN LOWER(name) LIKE '%general pants%' THEN 'Apparel'
  -- Destinations
  WHEN LOWER(name) LIKE '%airbnb%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%hotel%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%travel%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%flight%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%webjet%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%booking%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%expedia%' THEN 'Destinations'
  WHEN LOWER(name) LIKE '%accor%' THEN 'Destinations'
  -- Entertainment
  WHEN LOWER(name) LIKE '%spotify%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%netflix%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%disney%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%hoyts%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%event cinema%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%cinema%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%playstation%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%xbox%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%nintendo%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%steam%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%google play%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%apple%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%itunes%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%amc%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%ticketek%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%ticketmaster%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%stan%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%foxtel%' THEN 'Entertainment'
  WHEN LOWER(name) LIKE '%kayo%' THEN 'Entertainment'
  -- Food & Drink
  WHEN LOWER(name) LIKE '%uber eats%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%doordash%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%menulog%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%deliveroo%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%grubhub%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%wine%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%beer%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%liquor%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%dan murphy%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%bws%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%coles%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%woolworths%' THEN 'Food & Drink'
  WHEN LOWER(name) LIKE '%aldi%' THEN 'Food & Drink'
  -- Home
  WHEN LOWER(name) LIKE '%ikea%' THEN 'Home'
  WHEN LOWER(name) LIKE '%bunnings%' THEN 'Home'
  WHEN LOWER(name) LIKE '%home%' THEN 'Home'
  WHEN LOWER(name) LIKE '%freedom%' THEN 'Home'
  WHEN LOWER(name) LIKE '%temple%' THEN 'Home'
  WHEN LOWER(name) LIKE '%kmart%' THEN 'Home'
  WHEN LOWER(name) LIKE '%target%' THEN 'Home'
  WHEN LOWER(name) LIKE '%bed bath%' THEN 'Home'
  WHEN LOWER(name) LIKE '%harvey norman%' THEN 'Home'
  WHEN LOWER(name) LIKE '%good guys%' THEN 'Home'
  WHEN LOWER(name) LIKE '%jb hi-fi%' THEN 'Home'
  -- Lifestyle
  WHEN LOWER(name) LIKE '%sephora%' THEN 'Lifestyle'
  WHEN LOWER(name) LIKE '%mecca%' THEN 'Lifestyle'
  WHEN LOWER(name) LIKE '%priceline%' THEN 'Lifestyle'
  WHEN LOWER(name) LIKE '%beauty%' THEN 'Lifestyle'
  WHEN LOWER(name) LIKE '%cosmetic%' THEN 'Lifestyle'
  WHEN LOWER(name) LIKE '%fragrance%' THEN 'Lifestyle'
  WHEN LOWER(name) LIKE '%pet%' THEN 'Lifestyle'
  -- Online Shopping
  WHEN LOWER(name) LIKE '%amazon%' THEN 'Online Shopping'
  WHEN LOWER(name) LIKE '%ebay%' THEN 'Online Shopping'
  WHEN LOWER(name) LIKE '%catch%' THEN 'Online Shopping'
  WHEN LOWER(name) LIKE '%wish%' THEN 'Online Shopping'
  -- Restaurants
  WHEN LOWER(name) LIKE '%starbucks%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%mcdonald%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%kfc%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%subway%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%domino%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%pizza%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%grill%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%burger%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%nando%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%restaurant%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%dining%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%cafe%' THEN 'Restaurants'
  WHEN LOWER(name) LIKE '%coffee%' THEN 'Restaurants'
  -- Wellness
  WHEN LOWER(name) LIKE '%spa%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%wellness%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%fitness%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%gym%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%yoga%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%massage%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%health%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%pharmacy%' THEN 'Wellness'
  WHEN LOWER(name) LIKE '%chemist%' THEN 'Wellness'
  ELSE 'Other'
END
WHERE category IS NULL OR category = 'Other';
